version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
  db:
      image: mysql:latest
      restart: always
      ports:
        - '3306'
      environment:
        MYSQL_ROOT_PASSWORD: mynewpassword
        MYSQL_DATABASE: nodemvc
        volumes: db-data:/var/lib/mysql/data
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data:
